/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS (Manually Fixed by Antigravity) */

import type { Buffer } from 'node:buffer';

export function triggerPanic(secret: string): void;
export function resetPanic(): void;
export function isPanicMode(): boolean;

export interface ModelMetric {
    model: string;
    count: number;
}

export interface MetricsSummary {
    totalTokens: number;
    modelBreakdown: Array<ModelMetric>;
    avgLatencyMs: number;
}

export interface D2LAdapter {
    id: string;
    fingerprint: string;
    sizeBytes: number;
    weightsHash: string;
}

export class VadEngine {
    constructor(threshold: number, silenceTimeoutMs: number);
    get lastRms(): number;
    processChunk(chunk: Buffer | Uint8Array): string;
}

export class BackchannelEngine {
    constructor(historyLimit: number, cooldownMs: number);
    processEnergy(rms: number): boolean;
}

export class MetricsEngine {
    constructor();
    recordTokens(model: string, count: number): void;
    recordLatency(ms: number): void;
    summarize(): MetricsSummary;
}

export class RatchetDedupe {
    constructor(ttlMs: number, maxSize: number);
    check(key: string, timestampMs?: number | undefined | null): boolean;
    clear(): void;
    size(): number;
}

export class SecurityEngine {
    constructor();
    detectInjection(text: string): string | null;
    redactPii(text: string): string;
    calculateEntropy(text: string): number;
}

export class HeartbeatManager {
    constructor(intervalMs: number);
    tick(): boolean;
    reset(): void;
}

export class D2LEngine {
    constructor(maxCacheSize: number);
    internalizeContext(docId: string, content: string): D2LAdapter;
    generatePersonalityAdapter(soulContent: string, historySummary: string): D2LAdapter;
    getActiveAdaptersCount(): number;
}
