
export const CHROMIUM_BUNDLE_IDS = new Set([
    "com.google.Chrome",
    "com.google.Chrome.beta",
    "com.google.Chrome.canary",
    "com.google.Chrome.dev",
    "com.brave.Browser",
    "com.brave.Browser.beta",
    "com.brave.Browser.nightly",
    "com.microsoft.Edge",
    "com.microsoft.EdgeBeta",
    "com.microsoft.EdgeDev",
    "com.microsoft.EdgeCanary",
    "org.chromium.Chromium",
    "com.vivaldi.Vivaldi",
    "com.operasoftware.Opera",
    "com.operasoftware.OperaGX",
    "com.yandex.desktop.yandex-browser",
    "company.thebrowser.Browser", // Arc
]);

export const CHROMIUM_DESKTOP_IDS = new Set([
    "google-chrome.desktop",
    "google-chrome-beta.desktop",
    "google-chrome-unstable.desktop",
    "brave-browser.desktop",
    "microsoft-edge.desktop",
    "microsoft-edge-beta.desktop",
    "microsoft-edge-dev.desktop",
    "microsoft-edge-canary.desktop",
    "chromium.desktop",
    "chromium-browser.desktop",
    "vivaldi.desktop",
    "vivaldi-stable.desktop",
    "opera.desktop",
    "opera-gx.desktop",
    "yandex-browser.desktop",
    "org.chromium.Chromium.desktop",
]);

export const CHROMIUM_EXE_NAMES = new Set([
    "chrome.exe",
    "msedge.exe",
    "brave.exe",
    "brave-browser.exe",
    "chromium.exe",
    "vivaldi.exe",
    "opera.exe",
    "launcher.exe",
    "yandex.exe",
    "yandexbrowser.exe",
    // mac/linux names
    "google chrome",
    "google chrome canary",
    "brave browser",
    "microsoft edge",
    "chromium",
    "chrome",
    "brave",
    "msedge",
    "brave-browser",
    "google-chrome",
    "google-chrome-stable",
    "google-chrome-beta",
    "google-chrome-unstable",
    "microsoft-edge",
    "microsoft-edge-beta",
    "microsoft-edge-dev",
    "microsoft-edge-canary",
    "chromium-browser",
    "vivaldi",
    "vivaldi-stable",
    "opera",
    "opera-stable",
    "opera-gx",
    "yandex-browser",
]);
