export const browserCoreExamples = [
  "zero browser status",
  "zero browser start",
  "zero browser stop",
  "zero browser tabs",
  "zero browser open https://example.com",
  "zero browser focus abcd1234",
  "zero browser close abcd1234",
  "zero browser screenshot",
  "zero browser screenshot --full-page",
  "zero browser screenshot --ref 12",
  "zero browser snapshot",
  "zero browser snapshot --format aria --limit 200",
  "zero browser snapshot --efficient",
  "zero browser snapshot --labels",
];

export const browserActionExamples = [
  "zero browser navigate https://example.com",
  "zero browser resize 1280 720",
  "zero browser click 12 --double",
  'zero browser type 23 "hello" --submit',
  "zero browser press Enter",
  "zero browser hover 44",
  "zero browser drag 10 11",
  "zero browser select 9 OptionA OptionB",
  "zero browser upload /tmp/file.pdf",
  'zero browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "zero browser dialog --accept",
  'zero browser wait --text "Done"',
  "zero browser evaluate --fn '(el) => el.textContent' --ref 7",
  "zero browser console --level error",
  "zero browser pdf",
];
