export const DEFAULT_ZERO_BROWSER_ENABLED = true;
export const DEFAULT_ZERO_BROWSER_CONTROL_URL = "http://127.0.0.1:18791";
export const DEFAULT_ZERO_BROWSER_COLOR = "#e63946";
export const DEFAULT_ZERO_BROWSER_PROFILE_NAME = "zero";
export const DEFAULT_BROWSER_DEFAULT_PROFILE_NAME = "chrome";
export const DEFAULT_AI_SNAPSHOT_MAX_CHARS = 80_000;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_MAX_CHARS = 10_000;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_DEPTH = 6;
