
export const GROUP_LABELS: Record<string, string> = {
    wizard: "Assistente",
    update: "Atualização",
    diagnostics: "Diagnóstico",
    logging: "Registros (Logs)",
    gateway: "Gateway",
    nodeHost: "Hospedeiro de Nós",
    agents: "Agentes",
    tools: "Ferramentas",
    messages: "Mensagens & Memória",
    commands: "Comandos",
    session: "Sessões",
    cron: "Tarefas Agendadas (Cron)",
    hooks: "Extensões (Hooks)",
    ui: "Interface Gráfica (UI)",
    browser: "Navegação Web",
    talk: "Voz & Fala (TTS/STT)",
    channels: "Canais de Comunicação",
    skills: "Habilidades (Skills)",
    plugins: "Plugins de Integração",
    discovery: "Descoberta de Serviços",
    presence: "Presença & Status",
    voicewake: "Despertar por Voz",
    environments: "Ambientes & Variáveis",
};

export const GROUP_ORDERS: Record<string, number> = {
    meta: 1,
    wizard: 10,
    update: 20,
    diagnostics: 30,
    gateway: 40,
    nodeHost: 50,
    agents: 60,
    tools: 70,
    messages: 80,
    commands: 85,
    session: 90,
    cron: 100,
    hooks: 110,
    ui: 120,
    browser: 130,
    talk: 140,
    channels: 150,
    skills: 200,
    plugins: 205,
    discovery: 210,
    presence: 220,
    voicewake: 230,
    environments: 240,
    logging: 900,
};
