
export const FIELD_LABELS: Record<string, string> = {
    "meta.lastTouchedVersion": "Última Versão Alterada",
    "meta.lastTouchedAt": "Última Alteração em",
    "update.channel": "Canal de Atualização",
    "update.checkOnStart": "Verificar ao Iniciar",
    "diagnostics.enabled": "Diagnóstico Ativado",
    "diagnostics.flags": "Flags de Diagnóstico",
    "diagnostics.otel.enabled": "OpenTelemetry Ativado",
    "diagnostics.otel.endpoint": "Endpoint OpenTelemetry",
    "diagnostics.otel.protocol": "Protocolo OpenTelemetry",
    "diagnostics.otel.headers": "Cabeçalhos OpenTelemetry",
    "diagnostics.otel.serviceName": "Nome do Serviço OpenTelemetry",
    "diagnostics.otel.traces": "Traces OpenTelemetry Ativados",
    "diagnostics.otel.metrics": "Métricas OpenTelemetry Ativadas",
    "diagnostics.otel.logs": "Logs OpenTelemetry Ativados",
    "diagnostics.otel.sampleRate": "Taxa de Amostragem (Trace)",
    "diagnostics.otel.flushIntervalMs": "Intervalo de Flush (ms)",
    "diagnostics.cacheTrace.enabled": "Rastro de Cache Ativado",
    "diagnostics.cacheTrace.filePath": "Caminho do Arquivo de Rastro",
    "diagnostics.cacheTrace.includeMessages": "Incluir Mensagens no Rastro",
    "diagnostics.cacheTrace.includePrompt": "Incluir Prompt no Rastro",
    "diagnostics.cacheTrace.includeSystem": "Incluir Sistema no Rastro",
    "agents.list.*.identity.avatar": "Avatar da Identidade",
    "gateway.remote.url": "URL do Gateway Remoto",
    "gateway.remote.sshTarget": "Alvo SSH do Gateway Remoto",
    "gateway.remote.sshIdentity": "Identidade SSH do Gateway Remoto",
    "gateway.remote.token": "Token do Gateway Remoto",
    "gateway.remote.password": "Senha do Gateway Remoto",
    "gateway.remote.tlsFingerprint": "Impressão Digital TLS Remota",
    "gateway.auth.token": "Token do Gateway",
    "gateway.auth.password": "Senha do Gateway",
    "gateway.auth.allowTailscale": "Permitir Tailscale",
    "gateway.bind": "Vínculo (Bind)",
    "wizard.lastRunAt": "Última Execução em",
    "wizard.lastRunCommand": "Último Comando Executado",
    "wizard.lastRunCommit": "Último Commit",
    "wizard.lastRunMode": "Último Modo",
    "wizard.lastRunVersion": "Última Versão Executada",
    "agents.defaults.compaction": "Compactação",
    "agents.defaults.compaction.mode": "Modo de Compactação",
    "agents.defaults.compaction.reserveTokensFloor": "Reserva de Tokens (Mínimo)",
    "agents.defaults.compaction.memoryFlush": "Limpeza de Memória (Memory Flush)",
    "agents.defaults.compaction.memoryFlush.enabled": "Ativado",
    "agents.defaults.compaction.memoryFlush.softThresholdTokens": "Limiar de Tokens (Soft)",
    "agents.defaults.compaction.memoryFlush.prompt": "Prompt de Compactação",
    "agents.defaults.compaction.memoryFlush.systemPrompt": "Prompt de Sistema para Compactação",
    "agents.defaults.blockStreamingDefault": "Streaming em Blocos (Padrão)",
    "agents.defaults.blockStreamingBreak": "Quebra de Streaming em Blocos",
    "agents.defaults.blockStreamingChunk": "Configuração de Fragmentos (Chunk)",
    "agents.defaults.blockStreamingChunk.minChars": "Caracteres Mínimos",
    "agents.defaults.blockStreamingChunk.maxChars": "Caracteres Máximos",
    "agents.defaults.blockStreamingChunk.breakPreference": "Preferência de Quebra",
    "agents.defaults.blockStreamingCoalesce": "Coalescência de Streaming",
    "agents.defaults.blockStreamingCoalesce.minChars": "Caracteres Mínimos",
    "agents.defaults.blockStreamingCoalesce.maxChars": "Caracteres Máximos",
    "agents.defaults.blockStreamingCoalesce.idleMs": "Tempo de Espera (ms)",
    "agents.defaults.cliBackends": "Backends de CLI",
    "agents.defaults.bootstrapMaxChars": "Máximo de Caracteres no Bootstrap",
    "agents.defaults.repoRoot": "Raiz do Repositório",
    "agents.defaults.workspace": "Espaço de Trabalho",
    "agents.defaults.models": "Modelos",
    "agents.defaults.model.primary": "Modelo Primário",
    "agents.defaults.model.fallbacks": "Fallbacks de Modelo",
    "agents.defaults.imageModel.primary": "Modelo de Imagem",
    "agents.defaults.imageModel.fallbacks": "Fallbacks de Modelo de Imagem",
    "tools.media.image.enabled": "Ativar Compreensão de Imagem",
    "tools.media.image.maxBytes": "Bytes Máximos de Imagem",
    "tools.media.image.maxChars": "Caracteres Máximos de Imagem",
    "tools.media.image.prompt": "Prompt de Compreensão de Imagem",
    "tools.media.image.timeoutSeconds": "Tempo Limite de Imagem (seg)",
    "tools.media.image.attachments": "Política de Anexos de Imagem",
    "tools.media.image.models": "Modelos de Compreensão de Imagem",
    "tools.media.image.scope": "Escopo de Compreensão de Imagem",
    "tools.media.models": "Modelos Compartilhados de Mídia",
    "tools.media.concurrency": "Concorrência de Mídia",
    "tools.media.audio.enabled": "Ativar Compreensão de Áudio",
    "tools.media.audio.maxBytes": "Bytes Máximos de Áudio",
    "tools.media.audio.maxChars": "Caracteres Máximos de Áudio",
    "tools.media.audio.prompt": "Prompt de Compreensão de Áudio",
    "tools.media.audio.timeoutSeconds": "Tempo Limite de Áudio (seg)",
    "tools.media.audio.language": "Idioma de Compreensão de Áudio",
    "tools.media.audio.attachments": "Política de Anexos de Áudio",
    "tools.media.audio.models": "Modelos de Compreensão de Áudio",
    "tools.media.audio.scope": "Escopo de Compreensão de Áudio",
    "tools.media.video.enabled": "Ativar Compreensão de Vídeo",
    "tools.media.video.maxBytes": "Bytes Máximos de Vídeo",
    "tools.media.video.maxChars": "Caracteres Máximos de Vídeo",
    "tools.media.video.prompt": "Prompt de Compreensão de Vídeo",
    "tools.media.video.timeoutSeconds": "Tempo Limite de Vídeo (seg)",
    "tools.media.video.attachments": "Política de Anexos de Vídeo",
    "tools.media.video.models": "Modelos de Compreensão de Vídeo",
    "tools.media.video.scope": "Escopo de Compreensão de Vídeo",
    "tools.links.enabled": "Ativar Compreensão de Links",
    "tools.links.maxLinks": "Máximo de Links",
    "tools.links.timeoutSeconds": "Tempo Limite de Links (seg)",
    "tools.links.models": "Modelos de Compreensão de Links",
    "tools.links.scope": "Escopo de Compreensão de Links",
    "tools.profile": "Perfil de Ferramentas",
    "agents.list[].tools.profile": "Perfil de Ferramentas do Agente",
    "tools.byProvider": "Política de Ferramentas por Provedor",
    "agents.list[].tools.byProvider": "Política de Ferramentas do Agente por Provedor",
    "tools.exec.applyPatch.enabled": "Ativar apply_patch",
    "tools.exec.applyPatch.allowModels": "Modelos Permitidos para apply_patch",
    "tools.exec.notifyOnExit": "Notificar ao Sair da Execução",
    "tools.exec.approvalRunningNoticeMs": "Aviso de Execução (ms)",
    "tools.exec.host": "Hospedeiro de Execução",
    "tools.exec.security": "Segurança de Execução",
    "tools.exec.ask": "Solicitar Confirmação",
    "tools.exec.node": "Vínculo de Nó de Execução",
    "tools.exec.pathPrepend": "Precedência de Caminho (PATH)",
    "tools.exec.safeBins": "Binários Seguros (Exec)",
    "tools.message.allowCrossContextSend": "Permitir Mensagens Multi-Contexto",
    "tools.message.crossContext.allowWithinProvider": "Permitir Multi-Contexto (Mesmo Provedor)",
    "tools.message.crossContext.allowAcrossProviders": "Permitir Multi-Contexto (Entre Provedores)",
    "tools.message.crossContext.marker.enabled": "Marcador de Multi-Contexto",
    "tools.message.crossContext.marker.prefix": "Prefixo do Marcador de Multi-Contexto",
    "tools.message.crossContext.marker.suffix": "Sufixo do Marcador de Multi-Contexto",
    "tools.message.broadcast.enabled": "Ativar Transmissão (Broadcast)",
    "tools.web.search.enabled": "Ativar Ferramenta de Busca Web",
    "tools.web.search.provider": "Provedor de Busca Web",
    "tools.web.search.apiKey": "Chave da API Brave Search",
    "tools.web.search.maxResults": "Máximo de Resultados de Busca",
    "tools.web.search.timeoutSeconds": "Tempo Limite de Busca (seg)",
    "tools.web.search.cacheTtlMinutes": "Tempo de Cache de Busca (min)",
    "tools.web.fetch.enabled": "Ativar Ferramenta de Captura Web",
    "tools.web.fetch.maxChars": "Máximo de Caracteres da Captura Web",
    "tools.web.fetch.timeoutSeconds": "Tempo Limite de Captura (seg)",
    "tools.web.fetch.cacheTtlMinutes": "Tempo de Cache de Captura (min)",
    "tools.web.fetch.maxRedirects": "Máximo de Redirecionamentos",
    "tools.web.fetch.userAgent": "User-Agent da Captura Web",
    "gateway.controlUi.basePath": "Caminho Base da Interface de Controle",
    "gateway.controlUi.allowInsecureAuth": "Permitir Autenticação Insegura na UI",
    "gateway.http.endpoints.chatCompletions.enabled": "Endpoint de Chat Completions (OpenAI)",
    "gateway.reload.mode": "Modo de Recarregamento de Configuração",
    "gateway.reload.debounceMs": "Debounce de Recarregamento (ms)",
    "gateway.nodes.browser.mode": "Modo de Navegador do Nó",
    "gateway.nodes.browser.node": "Vínculo de Nó de Navegador",
    "gateway.nodes.allowCommands": "Comandos Permitidos (Extra)",
    "gateway.nodes.denyCommands": "Comandos Bloqueados",
    "nodeHost.browserProxy.enabled": "Proxy de Navegador do Nó Ativado",
    "nodeHost.browserProxy.allowProfiles": "Perfis de Navegador Permitidos",
    "skills.load.watch": "Monitorar Habilidades (Watch)",
    "skills.load.watchDebounceMs": "Debounce de Monitoramento (ms)",
    "agents.defaults.envelopeTimezone": "Fuso Horário do Envelope",
    "agents.defaults.envelopeTimestamp": "Timestamp do Envelope",
    "agents.defaults.envelopeElapsed": "Tempo Decorrido no Envelope",
    "agents.defaults.memorySearch": "Busca em Memória",
    "agents.defaults.memorySearch.enabled": "Ativar Busca em Memória",
    "agents.defaults.memorySearch.sources": "Fontes de Busca em Memória",
    "agents.defaults.memorySearch.experimental.sessionMemory":
        "Índice de Memória de Sessão (Experimental)",
    "agents.defaults.memorySearch.provider": "Provedor de Busca em Memória",
    "agents.defaults.memorySearch.remote.baseUrl": "URL Base de Embedding Remoto",
    "agents.defaults.memorySearch.remote.apiKey": "Chave da API de Embedding Remoto",
    "agents.defaults.memorySearch.remote.headers": "Cabeçalhos de Embedding Remoto",
    "agents.defaults.memorySearch.remote.batch.concurrency": "Concorrência em Lote Remota",
    "agents.defaults.memorySearch.model": "Modelo de Busca em Memória",
    "agents.defaults.memorySearch.fallback": "Fallback de Busca em Memória",
    "agents.defaults.memorySearch.local.modelPath": "Caminho do Modelo de Embedding Local",
    "agents.defaults.memorySearch.store.path": "Caminho do Índice de Memória",
    "agents.defaults.memorySearch.store.vector.enabled": "Índice Vetorial de Memória",
    "agents.defaults.memorySearch.store.vector.extensionPath": "Caminho da Extensão Vetorial",
    "agents.defaults.memorySearch.chunking.tokens": "Tokens por Fragmento de Memória",
    "agents.defaults.memorySearch.chunking.overlap": "Tokens de Sobreposição de Memória",
    "agents.defaults.memorySearch.sync.onSessionStart": "Indexar ao Iniciar Sessão",
    "agents.defaults.memorySearch.sync.onSearch": "Indexar na Busca (Lazy)",
    "agents.defaults.memorySearch.sync.watch": "Monitorar Arquivos de Memória",
    "agents.defaults.memorySearch.sync.watchDebounceMs": "Debounce de Memória (ms)",
    "agents.defaults.memorySearch.sync.sessions.deltaBytes": "Delta de Bytes da Sessão",
    "agents.defaults.memorySearch.sync.sessions.deltaMessages": "Delta de Mensagens da Sessão",
    "agents.defaults.memorySearch.query.maxResults": "Resultados Máximos da Busca",
    "agents.defaults.memorySearch.query.minScore": "Pontuação Mínima da Busca",
    "agents.defaults.memorySearch.query.hybrid.enabled": "Busca Híbrida de Memória",
    "agents.defaults.memorySearch.query.hybrid.vectorWeight": "Peso Vetorial (Híbrido)",
    "agents.defaults.memorySearch.query.hybrid.textWeight": "Peso de Texto (Híbrido)",
    "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
        "Multiplicador de Candidatos Híbridos",
    "agents.defaults.memorySearch.cache.enabled": "Cache de Embedding de Memória",
    "agents.defaults.memorySearch.cache.maxEntries": "Máximo de Entradas no Cache de Embedding",
    "auth.profiles": "Perfis de Autenticação",
    "auth.order": "Ordem dos Perfis de Autenticação",
    "auth.cooldowns.billingBackoffHours": "Intervalo de Faturamento (horas)",
    "auth.cooldowns.billingBackoffHoursByProvider": "Overrides de Intervalo de Faturamento",
    "auth.cooldowns.billingMaxHours": "Limite de Intervalo de Faturamento (horas)",
    "auth.cooldowns.failureWindowHours": "Janela de Failover (horas)",
    "agents.defaults.humanDelay.mode": "Modo de Atraso Humano",
    "agents.defaults.humanDelay.minMs": "Atraso Humano Mínimo (ms)",
    "agents.defaults.humanDelay.maxMs": "Atraso Humano Máximo (ms)",
    "commands.native": "Comandos Nativos",
    "commands.nativeSkills": "Comandos de Habilidades Nativas",
    "commands.text": "Comandos de Texto",
    "commands.bash": "Permitir Comando Bash no Chat",
    "commands.bashForegroundMs": "Janela de Primeiro Plano Bash (ms)",
    "commands.config": "Permitir /config",
    "commands.debug": "Permitir /debug",
    "commands.restart": "Permitir Reinício",
    "commands.useAccessGroups": "Usar Grupos de Acesso",
    "ui.seamColor": "Cor de Destaque",
    "ui.assistant.name": "Nome do Assistente",
    "ui.assistant.avatar": "Avatar do Assistente",
    "browser.controlUrl": "URL de Controle do Navegador",
    "browser.snapshotDefaults": "Padrões de Instantâneo (Snapshot)",
    "browser.snapshotDefaults.mode": "Modo de Instantâneo",
    "browser.remoteCdpTimeoutMs": "Tempo Limite de CDP Remoto (ms)",
    "browser.remoteCdpHandshakeTimeoutMs": "Tempo Limite de Handshake CDP (ms)",
    "session.dmScope": "Escopo da Sessão de DM",
    "session.agentToAgent.maxPingPongTurns": "Turnos de Ping-Pong Agente-Agente",
    "messages.ackReaction": "Emoji de Reação de Confirmação",
    "messages.ackReactionScope": "Escopo da Reação de Confirmação",
    "messages.inbound.debounceMs": "Debounce de Mensagens Recebidas (ms)",
    "talk.apiKey": "Chave da API Talk",
    "channels.telegram.botToken": "Token do Bot do Telegram",
    "channels.telegram.dmPolicy": "Política de DM do Telegram",
    "channels.telegram.streamMode": "Modo de Streaming do Telegram",
    "channels.telegram.draftChunk.minChars": "Caracteres Mínimos do Fragmento",
    "channels.telegram.draftChunk.maxChars": "Caracteres Máximos do Fragmento",
    "channels.telegram.draftChunk.breakPreference": "Preferência de Quebra do Fragmento",
    "channels.telegram.retry.attempts": "Tentativas de Re-execução do Telegram",
    "channels.telegram.retry.minDelayMs": "Atraso Mínimo de Re-execução (ms)",
    "channels.telegram.retry.maxDelayMs": "Atraso Máximo de Re-execução (ms)",
    "channels.telegram.retry.jitter": "Jitter de Re-execução (Telegram)",
    "channels.telegram.timeoutSeconds": "Tempo Limite da API do Telegram (seg)",
    "channels.telegram.capabilities.inlineButtons": "Botões Inline do Telegram",
    "channels.whatsapp.dmPolicy": "Política de DM do WhatsApp",
    "channels.whatsapp.selfChatMode": "Modo de Auto-Chat do WhatsApp",
    "channels.whatsapp.debounceMs": "Debounce de Mensagens do WhatsApp (ms)",
    "channels.signal.dmPolicy": "Política de DM do Signal",
    "channels.imessage.dmPolicy": "Política de DM do iMessage",
    "channels.bluebubbles.dmPolicy": "Política de DM do BlueBubbles",
    "channels.discord.dm.policy": "Política de DM do Discord",
    "channels.discord.retry.attempts": "Tentativas de Re-execução do Discord",
    "channels.discord.retry.minDelayMs": "Atraso Mínimo de Re-execução (ms)",
    "channels.discord.retry.maxDelayMs": "Atraso Máximo de Re-execução (ms)",
    "channels.discord.retry.jitter": "Jitter de Re-execução (Discord)",
    "channels.discord.maxLinesPerMessage": "Máximo de Linhas por Mensagem (Discord)",
    "channels.slack.dm.policy": "Política de DM do Slack",
    "channels.slack.allowBots": "Permitir Mensagens de Bots no Slack",
    "channels.discord.token": "Token do Bot do Discord",
    "channels.slack.botToken": "Token do Bot do Slack",
    "channels.slack.appToken": "Token do App do Slack",
    "channels.slack.userToken": "Token de Usuário do Slack",
    "channels.slack.userTokenReadOnly": "Token de Usuário do Slack (Apenas Leitura)",
    "channels.slack.thread.historyScope": "Escopo do Histórico de Threads no Slack",
    "channels.slack.thread.inheritParent": "Herança de Pai na Thread do Slack",
    "channels.mattermost.botToken": "Token do Bot do Mattermost",
    "channels.mattermost.baseUrl": "URL Base do Mattermost",
    "channels.mattermost.chatmode": "Modo de Chat do Mattermost",
    "channels.mattermost.oncharPrefixes": "Prefixos onchar do Mattermost",
    "channels.mattermost.requireMention": "Exigir Menção no Mattermost",
    "channels.signal.account": "Conta do Signal",
    "channels.imessage.cliPath": "Caminho da CLI do iMessage",
    "agents.list[].identity.avatar": "Avatar do Agente",
    "plugins.enabled": "Ativar Plugins",
    "plugins.allow": "Lista de Permissões de Plugins",
    "plugins.deny": "Lista de Bloqueio de Plugins",
    "plugins.load.paths": "Caminhos de Carga de Plugins",
    "plugins.slots": "Slots de Plugins",
    "plugins.slots.memory": "Plugin de Memória",
    "plugins.entries": "Entradas de Plugins",
    "plugins.entries.*.enabled": "Plugin Ativado",
    "plugins.entries.*.config": "Configuração do Plugin",
    "plugins.installs": "Registros de Instalação de Plugins",
    "plugins.installs.*.source": "Fonte de Instalação do Plugin",
    "plugins.installs.*.spec": "Especificação da Instalação",
    "plugins.installs.*.sourcePath": "Caminho de Origem da Instalação",
    "plugins.installs.*.installPath": "Caminho de Instalação",
    "plugins.installs.*.version": "Versão da Instalação",
    "plugins.installs.*.installedAt": "Hora da Instalação",
    "environments.templates.*.name": "Nome do Template",
    "environments.templates.*.description": "Descrição do Ambiente",
    "environments.templates.*.image": "Imagem Docker",
    "environments.templates.*.tools": "Ferramentas Autorizadas",
    "environments.templates.*.env": "Variáveis de Ambiente",
    "environments.templates.*.mounts": "Volumes Montados (Binds)",
};

export const FIELD_PLACEHOLDERS: Record<string, string> = {
    "gateway.remote.url": "ws://host:18789",
    "gateway.remote.tlsFingerprint": "sha256:ab12cd34…",
    "gateway.remote.sshTarget": "user@host",
    "gateway.controlUi.basePath": "/zero",
    "channels.mattermost.baseUrl": "https://chat.example.com",
    "agents.list[].identity.avatar": "avatars/zero.png",
};
